// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajqaycyrfltijnkhoezc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqcWF5Y3lyZmx0aWpua2hvZXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MjA2NTMsImV4cCI6MjA2MjM5NjY1M30.Vx3WduxV-D9irNxZQSIziGxvbsKAMVEaE3Q8NqE9a1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

console.log('Initializing Supabase client with URL:', SUPABASE_URL);
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
console.log('Supabase client initialized successfully');